config/routes.rb
Frecipe::Application.routes.draw do

  resources :events

  get "metrics" => "metrics#index"
  get "metrics/show"

  resources :feedbacks
  resources :rankings do
    collection do
      get 'facebook'
    end
  end

  resources :grocery_recipes do
    collection do
      post 'multiple_delete'
    end
  end
  devise_for :user_sessions

  resources :notifications do
    collection do
      post 'user'
      post 'check'
    end
  end

  resources :comments

  match 'groceries/list' => "groceries#list"
  match 'groceries/multiple_delete' => "groceries#multiple_delete"
  resources :groceries do 
    collection do
      post 'fridge'
      post 'recover'
    end
  end

  resources :likes

  resources :follows

  resources :user_ingredients
  match 'user_ingredients/multiple_delete' => "user_ingredients#multiple_delete"
  resources :recipe_ingredients

  match 'recipes/user' => "recipes#user"
  match 'recipes/detail' => "recipes#detail"
  match 'recipes/possible' => "recipes#possible"
  post 'recipes/rate' => "recipes#rate"
  resources :recipes

  resources :ingredients

  match 'users/auth/failure', to: redirect('/')
  devise_for :users, :controllers => { :registrations => "registrations" }

  match 'tokens/show' => "tokens#show"
  match 'tokens/detail' => "tokens#detail"

  resources :tokens do
    collection do
      post 'profile'
      post 'reset'
      post 'password'
      post 'facebook_check'
      put 'update'
      post 'picture'
      get 'facebookAccounts'
      get 'search'
      get 'liked/:id' => "tokens#liked"
      get 'likes/:id' => "tokens#likes"
      get 'followers/:id' => "tokens#followers"
      get 'following/:id' => "tokens#following"
      get 'tokens/:id' => "tokens#check"

    end
  end

  
  root :to => "user_sessions#index"

end

app/models/grocery_recipe.rb
class GroceryRecipe < ActiveRecord::Base
  # attr_accessible :title, :body

  belongs_to :user
  belongs_to :recipe

  has_many :groceries, :dependent => :destroy
  has_many :ingredient_relationships, :class_name => "Grocery", :foreign_key => "grocery_recipe_id"
  has_many :ingredients, :through => :ingredient_relationships, :source => :ingredient
  attr_accessible :user, :recipe, :user_id, :recipe_id

end

app/controllers/grocery_recipes_controller.rb
class GroceryRecipesController < ApplicationController
  # GET /grocery_recipes
  # GET /grocery_recipes.json
  def index
    @grocery_recipes = GroceryRecipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @grocery_recipes }
    end
  end

  # GET /grocery_recipes/1
  # GET /grocery_recipes/1.json
  def show
    @grocery_recipe = GroceryRecipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @grocery_recipe }
    end
  end

  # GET /grocery_recipes/new
  # GET /grocery_recipes/new.json
  def new
    @grocery_recipe = GroceryRecipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @grocery_recipe }
    end
  end

  # GET /grocery_recipes/1/edit
  def edit
    @grocery_recipe = GroceryRecipe.find(params[:id])
  end

  # POST /grocery_recipes
  # POST /grocery_recipes.json
  def create
    user = UserSession.user_by_authentication_token(params[:authentication_token])
    groceryRecipe = GroceryRecipe.find_or_create_by_user_id_and_recipe_id(user.id, params[:recipe_id])
    groceryRecipe.recipe_groceries.destroy_all
    @groceries = []

    if params[:groceries]
      names = params[:groceries].split(',')
      for name in names
        ingredient = Ingredient.find_or_create_by_name(name.downcase.titleize)
        grocery = RecipeGrocery.new(:grocery_recipe => groceryRecipe, :ingredient => ingredient)
        if grocery.save
          @groceries << grocery
        end
      end
    end
    respond_to do |format|
      if @groceries.length > 0
        format.json { render :json => { :groceries => @groceries}}
      else
        format.json { render :json => { :message => "Nothing to add"}}
      end
    end
  end

  # PUT /grocery_recipes/1
  # PUT /grocery_recipes/1.json
  def update
    @grocery_recipe = GroceryRecipe.find(params[:id])

    respond_to do |format|
      if @grocery_recipe.update_attributes(params[:grocery_recipe])
        format.html { redirect_to @grocery_recipe, notice: 'Grocery recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grocery_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grocery_recipes/1
  # DELETE /grocery_recipes/1.json
  def destroy
    user = UserSession.user_by_authentication_token(params[:authentication_token])
    @grocery_recipe = GroceryRecipe.find(params[:id])

    message = "failure"
    if user == @grocery_recipe.user
      @grocery_recipe.destroy
      message =  "success"
    end
    
    respond_to do |format|
      format.json { render :json => { :message => message, :grocery_list => user.grocery_list }}
    end
  end

  # custom methods
  def multiple_delete
    user = UserSession.user_by_authentication_token(params[:authentication_token])
    respond_to do |format|
      if user
        ids = params[:ids]
        if ids
          user.grocery_recipes.where(:id => ids).destroy_all
          format.json { render :json => { :message => "succcess", :grocery_list => user.grocery_list }}
        end

      else
        format.json { render :json => { :message => "failure"}, :status => 404}
      end
    end 

  end
end

app/helpers/grocery_recipes_helper.rb
module GroceryRecipesHelper
end

app/views/grocery_recipes/_form.html.erb
<%= form_for(@grocery_recipe) do |f| %>
  <% if @grocery_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grocery_recipe.errors.count, "error") %> prohibited this grocery_recipe from being saved:</h2>

      <ul>
      <% @grocery_recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grocery_recipes/edit.html.erb
<h1>Editing grocery_recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @grocery_recipe %> |
<%= link_to 'Back', grocery_recipes_path %>

app/views/grocery_recipes/index.html.erb
<h1>Listing grocery_recipes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @grocery_recipes.each do |grocery_recipe| %>
  <tr>
    <td><%= link_to 'Show', grocery_recipe %></td>
    <td><%= link_to 'Edit', edit_grocery_recipe_path(grocery_recipe) %></td>
    <td><%= link_to 'Destroy', grocery_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Grocery recipe', new_grocery_recipe_path %>

app/views/grocery_recipes/new.html.erb
<h1>New grocery_recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', grocery_recipes_path %>

app/views/grocery_recipes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_grocery_recipe_path(@grocery_recipe) %> |
<%= link_to 'Back', grocery_recipes_path %>