config/routes.rb
Frecipe::Application.routes.draw do

  resources :events

  get "metrics" => "metrics#index"
  get "metrics/show"

  resources :feedbacks
  resources :rankings do
    collection do
      get 'facebook'
    end
  end

  resources :grocery_recipes do
    collection do
      post 'multiple_delete'
    end
  end
  devise_for :user_sessions

  resources :notifications do
    collection do
      post 'user'
      post 'check'
    end
  end

  resources :comments

  match 'groceries/list' => "groceries#list"
  match 'groceries/multiple_delete' => "groceries#multiple_delete"
  resources :groceries do 
    collection do
      post 'fridge'
      post 'recover'
    end
  end

  resources :likes

  resources :follows

  resources :user_ingredients
  match 'user_ingredients/multiple_delete' => "user_ingredients#multiple_delete"
  resources :recipe_ingredients

  match 'recipes/user' => "recipes#user"
  match 'recipes/detail' => "recipes#detail"
  match 'recipes/possible' => "recipes#possible"
  post 'recipes/rate' => "recipes#rate"
  resources :recipes

  resources :ingredients

  match 'users/auth/failure', to: redirect('/')
  devise_for :users, :controllers => { :registrations => "registrations" }

  match 'tokens/show' => "tokens#show"
  match 'tokens/detail' => "tokens#detail"

  resources :tokens do
    collection do
      post 'profile'
      post 'reset'
      post 'password'
      post 'facebook_check'
      put 'update'
      post 'picture'
      get 'facebookAccounts'
      get 'search'
      get 'liked/:id' => "tokens#liked"
      get 'likes/:id' => "tokens#likes"
      get 'followers/:id' => "tokens#followers"
      get 'following/:id' => "tokens#following"
      get 'tokens/:id' => "tokens#check"

    end
  end

  
  root :to => "user_sessions#index"

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  # attr_accessible :title, :body
  default_scope order('name')

  has_many :recipe_relationships, :class_name => "RecipeIngredient", :foreign_key => "recipe_id"
  has_many :recipes, :through => :recipe_relationships, :source => :recipe
  attr_accessible :name, :image

  has_attached_file :image, :path => "public/image/ingredients/:id/:filename", :url => "image/ingredients/:id/:filename", :default_url => "https://s3.amazonaws.com/FrecipeProduction/public/image/ingredients/default_ingredient_image.png", :s3_permissions => "public_read_write"
  validates_attachment_size :image, :less_than => 5.megabytes
	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

	validates :name, :uniqueness => true
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  
  # GET /ingredients
  # GET /ingredients.json
  def index
    # @ingredients = Ingredient.all.map { |ingredient| ingredient.name }
    @ingredients = Ingredient.all.map { |ingredient| ingredient.name }
    @ingredients_hash = Ingredient.all
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.json
  def new
    @ingredient = Ingredient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(:name => params[:ingredient][:name].titleize, :image => params[:ingredient][:image])

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render json: @ingredient, status: :created, location: @ingredient }
      else
        format.html { render action: "new" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.json
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to ingredients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/_form.html.erb
<%= form_for @ingredient, :html => { :multipart => true } do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    
  <% end %>
  <%= f.text_field :name %><br>
  <%= f.file_field :image %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing <%= @ingredient.name %></h1>
<%= image_tag @ingredient.image.url %>
<%= render 'form' %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ingredients_hash.each do |ingredient| %>
  <tr>
    <td><%= image_tag ingredient.image.url, :width => 100, :height => 100 %>
    <td><%= link_to ingredient.name, ingredient %></td>
    <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
    <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render 'form' %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @ingredient.image.url %>
<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>