config/routes.rb
Frecipe::Application.routes.draw do

  resources :events

  get "metrics" => "metrics#index"
  get "metrics/show"

  resources :feedbacks
  resources :rankings do
    collection do
      get 'facebook'
    end
  end

  resources :grocery_recipes do
    collection do
      post 'multiple_delete'
    end
  end
  devise_for :user_sessions

  resources :notifications do
    collection do
      post 'user'
      post 'check'
    end
  end

  resources :comments

  match 'groceries/list' => "groceries#list"
  match 'groceries/multiple_delete' => "groceries#multiple_delete"
  resources :groceries do 
    collection do
      post 'fridge'
      post 'recover'
    end
  end

  resources :likes

  resources :follows

  resources :user_ingredients
  match 'user_ingredients/multiple_delete' => "user_ingredients#multiple_delete"
  resources :recipe_ingredients

  match 'recipes/user' => "recipes#user"
  match 'recipes/detail' => "recipes#detail"
  match 'recipes/possible' => "recipes#possible"
  post 'recipes/rate' => "recipes#rate"
  resources :recipes

  resources :ingredients

  match 'users/auth/failure', to: redirect('/')
  devise_for :users, :controllers => { :registrations => "registrations" }

  match 'tokens/show' => "tokens#show"
  match 'tokens/detail' => "tokens#detail"

  resources :tokens do
    collection do
      post 'profile'
      post 'reset'
      post 'password'
      post 'facebook_check'
      put 'update'
      post 'picture'
      get 'facebookAccounts'
      get 'search'
      get 'liked/:id' => "tokens#liked"
      get 'likes/:id' => "tokens#likes"
      get 'followers/:id' => "tokens#followers"
      get 'following/:id' => "tokens#following"
      get 'tokens/:id' => "tokens#check"

    end
  end

  
  root :to => "user_sessions#index"

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :content, :type, :user, :user_id
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    # @feedback = Feedback.new(params[:feedback])

    # respond_to do |format|
    #   if @feedback.save
    #     format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
    #     format.json { render json: @feedback, status: :created, location: @feedback }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @feedback.errors, status: :unprocessable_entity }
    #   end
    # end
    user = UserSession.user_by_authentication_token(params[:authentication_token])
    respond_to do |format|
      if user
        @feedback = Feedback.create(:user_id => user.id, :content => params[:content])
        format.json { render :json => { :message => "success"}}
      else
        format.json { render :json => { :message => "failure"}, :status => 404 }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.type %></td>
    <td><%= feedback.content %></td>
    <td><%= link_to 'Show', feedback %></td>
    <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
    <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @feedback.type %>
</p>

<p>
  <b>Content:</b>
  <%= @feedback.content %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>