config/routes.rb
Frecipe::Application.routes.draw do

  resources :events

  get "metrics" => "metrics#index"
  get "metrics/show"

  resources :feedbacks
  resources :rankings do
    collection do
      get 'facebook'
    end
  end

  resources :grocery_recipes do
    collection do
      post 'multiple_delete'
    end
  end
  devise_for :user_sessions

  resources :notifications do
    collection do
      post 'user'
      post 'check'
    end
  end

  resources :comments

  match 'groceries/list' => "groceries#list"
  match 'groceries/multiple_delete' => "groceries#multiple_delete"
  resources :groceries do 
    collection do
      post 'fridge'
      post 'recover'
    end
  end

  resources :likes

  resources :follows

  resources :user_ingredients
  match 'user_ingredients/multiple_delete' => "user_ingredients#multiple_delete"
  resources :recipe_ingredients

  match 'recipes/user' => "recipes#user"
  match 'recipes/detail' => "recipes#detail"
  match 'recipes/possible' => "recipes#possible"
  post 'recipes/rate' => "recipes#rate"
  resources :recipes

  resources :ingredients

  match 'users/auth/failure', to: redirect('/')
  devise_for :users, :controllers => { :registrations => "registrations" }

  match 'tokens/show' => "tokens#show"
  match 'tokens/detail' => "tokens#detail"

  resources :tokens do
    collection do
      post 'profile'
      post 'reset'
      post 'password'
      post 'facebook_check'
      put 'update'
      post 'picture'
      get 'facebookAccounts'
      get 'search'
      get 'liked/:id' => "tokens#liked"
      get 'likes/:id' => "tokens#likes"
      get 'followers/:id' => "tokens#followers"
      get 'following/:id' => "tokens#following"
      get 'tokens/:id' => "tokens#check"

    end
  end

  
  root :to => "user_sessions#index"

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user, :class_name => "User"
  belongs_to :follower, :class_name => "User"

  attr_accessible :user, :follower, :user_id, :follower_id
  validates :user_id, :uniqueness => { :scope => :follower_id }
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  # GET /follows
  # GET /follows.json
  def index
    @follows = Follow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @follows }
    end
  end

  # GET /follows/1
  # GET /follows/1.json
  def show
    @follow = Follow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @follow }
    end
  end

  # GET /follows/new
  # GET /follows/new.json
  def new
    @follow = Follow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @follow }
    end
  end

  # GET /follows/1/edit
  def edit
    @follow = Follow.find(params[:id])
  end

  # POST /follows
  # POST /follows.json
  def create
    # @follow = Follow.new(params[:follow])

    # respond_to do |format|
    #   if @follow.save
    #     format.html { redirect_to @follow, notice: 'Follow was successfully created.' }
    #     format.json { render json: @follow, status: :created, location: @follow }
    #   else
    #     format.html { render action: "new" }
    #     format.json { render json: @follow.errors, status: :unprocessable_entity }
    #   end
    # end

    user = UserSession.user_by_authentication_token(params[:authentication_token])

    follow = User.find_by_id(params[:followId])

    respond_to do |format|
      if user
        if follow
          @follow = Follow.new(:user => follow, :follower => user)
          if @follow.save
            Notification.create(:source => user, :target => follow, :category => "follow", :seen => 0)
            format.json { render :json => { :message => "Following"}}
            follow.give_points(10)
          else
            @follow = Follow.find_by_user_id_and_follower_id(follow.id, user.id)
            @follow.destroy
            follow.give_points(-10)
            format.json { render :json => { :message => "Follow"}}
          end
        else
          format.json { render :json => { :message => "Invalid user selected."}}
        end
      else
        format.json { render :json => { :message => "Invalid authentication token"}}
      end
    end
  end

  # PUT /follows/1
  # PUT /follows/1.json
  def update
    @follow = Follow.find(params[:id])

    respond_to do |format|
      if @follow.update_attributes(params[:follow])
        format.html { redirect_to @follow, notice: 'Follow was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @follow.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /follows/1
  # DELETE /follows/1.json
  def destroy
    @follow = Follow.find(params[:id])
    @follow.destroy

    respond_to do |format|
      format.html { redirect_to follows_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_form.html.erb
<%= form_for(@follow) do |f| %>
  <% if @follow.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follow.errors.count, "error") %> prohibited this follow from being saved:</h2>

      <ul>
      <% @follow.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/follows/edit.html.erb
<h1>Editing follow</h1>

<%= render 'form' %>

<%= link_to 'Show', @follow %> |
<%= link_to 'Back', follows_path %>

app/views/follows/index.html.erb
<h1>Listing follows</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @follows.each do |follow| %>
  <tr>
    <td><%= link_to 'Show', follow %></td>
    <td><%= link_to 'Edit', edit_follow_path(follow) %></td>
    <td><%= link_to 'Destroy', follow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Follow', new_follow_path %>

app/views/follows/new.html.erb
<h1>New follow</h1>

<%= render 'form' %>

<%= link_to 'Back', follows_path %>

app/views/follows/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_follow_path(@follow) %> |
<%= link_to 'Back', follows_path %>